User defined selection
uppittu11/analysis pull request #49
Opened 2020-04-09 20:28 UTC by chrisiacovella

I just added in a simple option to allow the user to pass a custom lipid selection to the code.

E.g.,  analyze -f trimmed_470.xtc -c confout.gro -o ao_chol1  -n 1  --reload --select='resname ffa24'

to just analyze ffa24

2020-04-09 23:02 UTC, uppittu11 requested changes
Thanks for this. I think the CI passed, but there was an error with uploading the coverage report to CodeCov. I'll try to troubleshoot that, but I think this PR is almost good to go

2020-04-09 23:02 UTC, uppittu11 commented on bin/analyze.py
> +            print("Error: selection does not include any atoms.")
This should raise an Exception. 
```suggestion
            raise ValueError("Error: selection does not include any atoms.")
```

2020-04-10 16:43 UTC, chrisiacovella commented
Changes made, but we still have the Python37 test failing.

2020-04-10 16:46 UTC, uppittu11 approved these changes

2020-04-10 16:46 UTC, merged